OwnerGPT.WebUI.Admin/Controllers/Abstract/BasePartialViewController.cs
using Microsoft.AspNetCore.Mvc;

namespace OwnerGPT.WebUI.Admin.Controllers.Abstract
{
    public partial class BasePartialViewController : Controller
    {
        [HttpGet("[action]")]
        public IActionResult GetPartialView(string viewName, string parameter) => PartialView(viewName, parameter);
    }
}

OwnerGPT.WebUI.Admin/Controllers/Abstract/RDBMSBaseController.cs
using Microsoft.AspNetCore.Mvc;
using OwnerGPT.Core.Services.Compositions;

namespace OwnerGPT.WebUI.Admin.Controllers.Abstract
{
    [Route("[controller]")]
    public class RDBMSBaseController<IService, T> : Controller where IService : CompositionBaseService<T> where T : class
    {
        public IService Service { get; set; }

        public RDBMSBaseController(IService service) => Service = service;

        [HttpGet("api/{id}")]
        public virtual async Task<IActionResult> Id(int id)
        {
            return Ok(await Service.RDBMSServiceBase.FindById(id));
        }

        [HttpGet("api")]
        public virtual async Task<IActionResult> GetAll(int? page)
        {
            return Ok(await Service.RDBMSServiceBase.GetAll(page));
        }

        [HttpGet("api/[action]")]
        public virtual async Task<IActionResult> Search(string property, string value, int? page)
        {
            return Ok(await Service.RDBMSServiceBase.SearchByProperty<string>(property, value, page));
        }

    }
}

OwnerGPT.WebUI.Admin/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using OwnerGPT.Core.Extensions;
using OwnerGPT.Core.Services;
using OwnerGPT.Models;
using OwnerGPT.Models.Abstracts.DTO;
using OwnerGPT.WebUI.Admin.Controllers.Abstract;

namespace OwnerGPT.WebUI.Admin.Controllers
{
    [Route("")]
    public class AccountController : RDBMSBaseController<AccountService, Account>
    {
        public AccountController(AccountService Service) : base(Service) { }

        [HttpGet]
        public IActionResult Login() => View();

        [HttpGet("[controller]/[action]")]
        public async Task<IActionResult> Manager(int? page) =>
            View(await Service.RDBMSServiceBase.GetAll(page));

        [HttpGet("[controller]/[action]")]
        public IActionResult RequestAccess() => View();

        [HttpGet("[controller]/[action]")]
        public async Task<IActionResult> SignOut()
        {
            await Service.SignOut();

            return RedirectToAction("Login");
        }

        [HttpPost("[controller]/[action]")]
        public async Task<IActionResult> SignIn([FromForm] CredentialsDTO credintalsDTO) =>
            await Service.SignIn(credintalsDTO)
                .Then(_ => RedirectToAction("Index", "Home"));
    }
}

OwnerGPT.WebUI.Admin/Controllers/AgentDocumentsController.cs
using Microsoft.AspNetCore.Mvc;
using OwnerGPT.Core.Services;
using OwnerGPT.Models.Agents;
using OwnerGPT.WebUI.Admin.Controllers.Abstract;

namespace OwnerGPT.WebUI.Admin.Controllers
{
    [Route("[controller]")]
    public class AgentDocumentsController : RDBMSBaseController<AgentDocumentsService, AgentDocument>
    {
        public AgentDocumentsController(AgentDocumentsService Service) : base(Service) { }

        [HttpPost]
        [DisableRequestSizeLimit]
        public async void Upload(IFormFile file)
        {
            Response.StatusCode = 200;
            Response.ContentType = "text/html";

            var streamWriter = new StreamWriter(Response.Body);

            await foreach (int progress in Service.StreamCreate(file))
            {
                await streamWriter.WriteLineAsync(progress.ToString());

                await streamWriter.FlushAsync();

                Thread.Sleep(100);
            }

        }

        // TODO: map agent
        [HttpGet("[action]/{documentId}")]
        public async Task<IActionResult> FetchPreview(int documentId) =>
            Ok(await Service.FetchPreview(documentId));

        [HttpGet("api")]
        public virtual async Task<IActionResult> GetAll() =>
            Ok(await Service.RDBMSServiceBase.GetAll());

    }
}

OwnerGPT.WebUI.Admin/Controllers/AgentsController.cs
using Microsoft.AspNetCore.Mvc;
using OwnerGPT.Core.Services;
using OwnerGPT.Models.Abstracts.Bindings;
using OwnerGPT.Models.Agents;
using OwnerGPT.WebUI.Admin.Controllers.Abstract;

namespace OwnerGPT.WebUI.Admin.Controllers
{
    [Route("[controller]")]
    public class AgentsController : RDBMSBaseController<AgentsService, Agent>
    {
        public AgentsController(AgentsService Service) : base(Service) { }

        public async Task<IActionResult> Index(int? page, string property = "name", string value = "") =>
            View(await Service.RDBMSServiceBase.SearchByProperty(property, value, page));

        [HttpGet("[action]/{agentId}")]
        public async Task<IActionResult> Configure(int agentId) =>
            View(await Service.RDBMSServiceBase.FindById(agentId));

        [HttpGet("[action]/{agentId}")]
        public IActionResult KnowledgeBase() =>
            View();

        [HttpGet("[action]/{agentId}")]
        public async Task<IActionResult> Chat(int agentId) =>
            View(await Service.RDBMSServiceBase.FindById(agentId));

        [HttpPost("[action]")]
        public async Task<IActionResult> Create([FromForm][Bind(AgentBinding.Create)] Agent agent)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState.ValidationState);
            }

            await Service.CreateDefault(agent);

            return RedirectToAction("Index");
        }

        [HttpPost("[action]")]
        public async Task<IActionResult> Update([FromForm][Bind(AgentBinding.Update)] Agent agent)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState.ValidationState);
            }

            await Service.UpdateConfiguration(agent);

            return RedirectToAction("Index");
        }

    }
}

OwnerGPT.WebUI.Admin/Controllers/GPTController.cs
using Microsoft.AspNetCore.Mvc;
using OwnerGPT.Core.Services;
using OwnerGPT.Models.Abstracts.DTO;
using OwnerGPT.WebUI.Admin.Controllers.Abstract;

namespace OwnerGPT.WebUI.Admin.Controllers
{
    [Route("[controller]")]
    public class GPTController : BasePartialViewController
    {
        private readonly GPTService StatelessGPT;

        public GPTController(GPTService statelessGPT) =>
            StatelessGPT = statelessGPT;

        [HttpPost("[action]/{agentId}")]
        public async Task StreamReplay([FromBody] GPTMessageInputDTO messageInput, int agentId, CancellationToken cancellationToken)
        {
            var streamWriter = new StreamWriter(Response.Body);

            await foreach (var replay in StatelessGPT.StreamReplay(messageInput.Message, agentId, cancellationToken))
            {
                await streamWriter.WriteAsync(replay);
                await streamWriter.FlushAsync();
            }
        }

    }
}

OwnerGPT.WebUI.Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OwnerGPT.WebUI.Admin.Controllers.Abstract;

namespace OwnerGPT.WebUI.Admin.Controllers
{
    [Route("[controller]")]
    public class HomeController : BasePartialViewController
    {
        public HomeController() { }

        [HttpGet("[action]")]
        public IActionResult Index() =>
            View();

        [HttpGet("[action]")]
        public IActionResult KnowledgeBase() =>
            View();

        [HttpGet("[action]")]
        public IActionResult Tutorial() =>
            View();
    }
}

OwnerGPT.WebUI.Admin/Views/Agents/Configure.cshtml
@model Agent

@{
    ViewData["Title"] = "Configure Agent";
}

<div class="relative rounded-lg overflow-hidden box-shadow bg-white py-5 px-8 my-4">
    <div class="mb-4 lg:mb-0 pb-5 pt-3">
        <h3 class="mb-2 text-xl font-bold text-gray-900">Agents</h3>
        <span class="text-base font-normal text-gray-500">Configure agent's settings</span>
    </div>
    <form id="agent-configuration-form" action="@Url.Action("Update", "Agents")" method="post" class="mx-auto mt-4">
        <div class="grid grid-cols-1 gap-x-8 gap-y-6 sm:grid-cols-2">
            <input name="id" value="@Model.Id" hidden />

            <div class="sm:col-span-2">
                <label for="name" class="block text-sm font-semibold leading-6 text-gray-900">Name</label>
                <label for="name" class="block text-sm font-semibold leading-6 text-gray-900 mt-1">
                    <span class="text-xs text-gray-500">(name of the agent)</span>
                </label>
                <div class="mt-2.5">
                    <input value="@Model.Name" type="text" name="name" id="name" autocomplete="name" class="bg-gray-100 cursor-not-allowed block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" readonly>
                </div>
            </div>

            <div class="sm:col-span-2">
                <label for="description" class="block text-sm font-semibold leading-6 text-gray-900">Description</label>
                <label for="description" class="block text-sm font-semibold leading-6 text-gray-900 mt-1"><span class="text-xs text-gray-500">(description for internal refrence)</span></label>
                <div class="mt-2.5">
                    <input value="@Model.Description" type="text" name="description" id="description" autocomplete="organization" class="bg-gray-100 cursor-not-allowed block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" readonly>
                </div>
            </div>

            <div class="sm:col-span-2">
                <label for="introduction" class="block text-sm font-semibold leading-6 text-gray-900">Introduction</label>
                <label for="introduction" class="block text-sm font-semibold leading-6 text-gray-900 mt-1"><span class="text-xs text-gray-500">(welcoming statement to be printed to user's dialog as welcome)</span></label>
                <div class="mt-2.5">
                    <input value="@Model.Introduction" type="text" name="introduction" id="introduction" autocomplete="organization" class="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" required>
                </div>
            </div>

            <div class="sm:col-span-2">
                <label for="instruction" class="block text-sm font-semibold leading-6 text-gray-900">Instruction</label>
                <label for="instruction" class="block text-sm font-semibold leading-6 text-gray-900 mt-1"><span class="text-xs text-gray-500">(define bot's identity and how the bot should react)</span></label>
                <div class="mt-2.5">
                    <textarea name="instruction" id="instruction" rows="4" class="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" required>@(Model.Instruction)</textarea>
                </div>
            </div>

            <div class="sm:col-span-2">
                <label class="relative inline-flex items-center cursor-pointer">
                    <input name="@Model.Active" type="checkbox" value="true" class="sr-only peer">
                    <div class="w-9 h-5 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-4 after:w-4 after:transition-all peer-checked:bg-blue-600"></div>
                    <span class="ml-3 text-sm text-sm text-gray-600">By selecting this, you activate the agent to the public</span>
                </label>
            </div>
        </div>
        <div class="mt-10">
            <a href="@(Url.Action("KnowledgeBase", "Agents") + "/" + Model.Id)" class="block mb-2 cursor-pointer w-full rounded-md bg-white-600 px-3.5 py-2.5 text-center text-sm font-semibold text-indigo-600 shadow-sm hover:bg-indigo-500 hover:text-white focus-visible:outline focus-visible:outline-2 border border-indigo-600 focus-visible:outline-offset-2 focus-visible:outline-white-600">Manage knowledge</a>
            <button id="submit-configuration" type="button" class="block w-full rounded-md bg-indigo-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Configure</button>
        </div>
    </form>
</div>

@section Scripts {
    <script>
        var submitConfigurationElement = document.querySelector("#submit-configuration");

        binding.clickToTrigger(submitConfigurationElement, configurationSubmitHandler);

        function configurationSubmitHandler(event) {
            const formAttributes = Object.fromEntries(new FormData(document.querySelector("#agent-configuration-form")));

            var formToSubmit = new FormData();

            formToSubmit.append("Agent.Id", formAttributes["id"]);
            formToSubmit.append("Agent.Description", formAttributes["description"]);
            formToSubmit.append("Agent.Introduction", formAttributes["introduction"]);
            formToSubmit.append("Agent.Instruction", formAttributes["instruction"]);

            fetch("@Url.Action("Update", "Agents")", {
                method: 'POST',
                body: formToSubmit
            }).then(_ => {
                window.location.href = "@Url.Action("Index", "Agents")";
            }).catch((error) => {
                console.error(error);
            });
        }

    </script>
}

OwnerGPT.WebUI.Admin/Views/Agents/Index.cshtml
@model List<Agent>

@{
    ViewData["Title"] = "Agents Managment";
}

<div class="relative rounded-lg overflow-hidden box-shadow bg-white py-5 px-8">
    <div class="mb-4 lg:mb-0 pb-5 pt-3">
        <h3 class="mb-2 text-xl font-bold text-gray-900">Agents</h3>
        <span class="text-base font-normal text-gray-500">This is a list of system's agents</span>
    </div>
    <form method="get" href="@Url.Action("Index", "Agents")">
        <div class="flex items-center bg-gray-200 rounded-md mt-8">
            <div class="pl-2">
                <svg class="fill-current text-gray-500 w-6 h-6" xmlns="http://www.w3.org/2000/svg"
                     viewBox="0 0 24 24">
                    <path class="heroicon-ui" d="M16.32 14.9l5.39 5.4a1 1 0 0 1-1.42 1.4l-5.38-5.38a8 8 0 1 1 1.41-1.41zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z" />
                </svg>
            </div>
            <input name="value" class="w-full px-2 py-5 rounded-md bg-gray-200 border-0 text-gray-700 leading-tight focus:outline-none focus:border-transparent focus:ring-0 focus:border-0 py-2 px-2" id="search" type="text" placeholder="Search Agents">
            <input name="property" value="name" hidden>
            <input type="submit" hidden />
        </div>
    </form>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 mt-6">

        <div class="card px-2 py-2 m-2 border border-gray-400 rounded-lg border-indigo-600 hover:shadow-md hover:border-opacity-0 transform hover:-translate-y-1 transition-all duration-200">
            <button data-modal-target="create-agent-modal" data-modal-toggle="create-agent-modal" class="w-[100%] h-[100%]">
                <div class="m-3">
                    <h2 class="text-lg text-left mb-2">
                        Create
                    </h2>
                    <div class="flex flex-row justify-between mt-[14px]">
                        <p class="font-light font-mono text-sm text-gray-700 hover:text-gray-900 transition-all duration-200">Create a new Agent</p>
                        <div>
                            <span class="text-sm text-indigo-600 font-mono bg-white inline rounded-sm mr-2 p-[4px] border border-indigo-600 align-top float-right">
                                <svg class="w-4 h-4 stroke-current" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 1v16M1 9h16" />
                                </svg>
                            </span>
                        </div>
                    </div>
                </div>
            </button>
        </div>

        @foreach (var agent in Model)
        {

            <div class="card px-2 py-2 m-2 border border-gray-400 rounded-lg border-indigo-600 hover:shadow-md hover:border-opacity-0 transform hover:-translate-y-1 transition-all duration-200">
                <div class="m-3">
                    <h2 class="text-lg mb-2">
                        @agent.Name
                        <span class="text-sm text-teal-800 font-mono bg-teal-100 inline rounded-full px-2 align-top float-right animate-pulse">Chatbot</span>
                    </h2>
                    <div class="flex flex-row justify-between mt-[14px]">
                        <p class="font-light font-mono text-sm text-gray-700 hover:text-gray-900 transition-all duration-200">@agent.Description</p>
                        <div>
                            @if (agent.Instruction != null)
                            {
                                <a href="@Url.Action("Chat", "Agents", new {agentId = agent.Id})">
                                    <span class="text-sm text-white font-mono bg-indigo-600 inline rounded-sm p-[4px] border align-top float-right">
                                        <svg class="w-4 h-4 stroke-current" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 8 14">
                                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 13 5.7-5.326a.909.909 0 0 0 0-1.348L1 1" />
                                        </svg>
                                    </span>
                                </a>
                            }
                            <a href="@Url.Action("Configure", "Agents", new {agentId = agent.Id})">
                                <span class="text-sm text-indigo-600 font-mono bg-white inline rounded-sm mr-2 p-[4px] border border-indigo-600 align-top float-right">
                                    <svg class="w-4 h-4 stroke-current" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M18 7.5h-.423l-.452-1.09.3-.3a1.5 1.5 0 0 0 0-2.121L16.01 2.575a1.5 1.5 0 0 0-2.121 0l-.3.3-1.089-.452V2A1.5 1.5 0 0 0 11 .5H9A1.5 1.5 0 0 0 7.5 2v.423l-1.09.452-.3-.3a1.5 1.5 0 0 0-2.121 0L2.576 3.99a1.5 1.5 0 0 0 0 2.121l.3.3L2.423 7.5H2A1.5 1.5 0 0 0 .5 9v2A1.5 1.5 0 0 0 2 12.5h.423l.452 1.09-.3.3a1.5 1.5 0 0 0 0 2.121l1.415 1.413a1.5 1.5 0 0 0 2.121 0l.3-.3 1.09.452V18A1.5 1.5 0 0 0 9 19.5h2a1.5 1.5 0 0 0 1.5-1.5v-.423l1.09-.452.3.3a1.5 1.5 0 0 0 2.121 0l1.415-1.414a1.5 1.5 0 0 0 0-2.121l-.3-.3.452-1.09H18a1.5 1.5 0 0 0 1.5-1.5V9A1.5 1.5 0 0 0 18 7.5Zm-8 6a3.5 3.5 0 1 1 0-7 3.5 3.5 0 0 1 0 7Z" />
                                    </svg>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<div id="create-agent-modal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow">
            <div class="px-6 py-6 lg:px-8">
                <h3 class="mb-4 text-xl font-medium text-gray-900">Create a new agent</h3>
                <form action="@Url.Action("Create", "Agents")" method="post" class="space-y-6">
                    <div>
                        <label for="name" class="block mb-2 text-sm font-medium text-gray-900">Name</label>
                        <input type="text" name="name" id="name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" placeholder="Agent's name" required>
                    </div>
                    <div>
                        <label for="description" class="block mb-2 text-sm font-medium text-gray-900">Description</label>
                        <textarea rows="4" type="text" name="description" id="description" placeholder="Describe agent's purpose" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" required></textarea>
                    </div>
                    <button type="submit" class="w-full text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:outline-none focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Create Agent</button>
                </form>
            </div>
        </div>
    </div>
</div> 

OwnerGPT.WebUI.Admin/Views/Home/Agents.cshtml
@model List<Agent>

@{
    ViewData["Title"] = "Agents Managment";
}

<div class="relative rounded-lg overflow-hidden box-shadow bg-white py-5 px-8">
    <div class="mb-4 lg:mb-0 pb-5 pt-3">
        <h3 class="mb-2 text-xl font-bold text-gray-900">Agents</h3>
        <span class="text-base font-normal text-gray-500">This is a list of system's agents</span>
    </div>
    <div class="flex flex-row-reverse mb-4 mt-1">
        <button data-modal-target="create-agent-modal" data-modal-toggle="create-agent-modal" type="button" class="text-white bg-indigo-600 hover:bg-indigo-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center mr-2">
            <svg class="fill-current w-3.5 h-3.5 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
                <path d="M6.5 9a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9ZM8 10H5a5.006 5.006 0 0 0-5 5v2a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-2a5.006 5.006 0 0 0-5-5Zm11-3h-2V5a1 1 0 0 0-2 0v2h-2a1 1 0 1 0 0 2h2v2a1 1 0 0 0 2 0V9h2a1 1 0 1 0 0-2Z" />
            </svg>
            Agent
        </button>
    </div>
    <div class="flex items-center bg-gray-200 rounded-md">
        <div class="pl-2">
            <svg class="fill-current text-gray-500 w-6 h-6" xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 24 24">
                <path class="heroicon-ui"
                      d="M16.32 14.9l5.39 5.4a1 1 0 0 1-1.42 1.4l-5.38-5.38a8 8 0 1 1 1.41-1.41zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z" />
            </svg>
        </div>
        <input class="w-full px-2 py-5 rounded-md bg-gray-200 border-0 text-gray-700 leading-tight focus:outline-none focus:border-transparent focus:ring-0 focus:border-0 py-2 px-2" id="search" type="text" placeholder="Search Agents">
    </div>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 mt-6">
        
        @foreach(var agent in Model)
        {
            <div class="card px-2 py-2 m-2 cursor-pointer border border-gray-400 rounded-lg border-indigo-600 hover:shadow-md hover:border-opacity-0 transform hover:-translate-y-1 transition-all duration-200">
                <div class="m-3">
                    <h2 class="text-lg mb-2">
                        @agent.Name
                        <span class="text-sm text-teal-800 font-mono bg-teal-100 inline rounded-full px-2 align-top float-right animate-pulse">Chatbot</span>
                    </h2>
                    <p class="font-light font-mono text-sm text-gray-700 hover:text-gray-900 transition-all duration-200">@agent.Description</p>
                </div>
            </div>
        }
    </div>
</div>

<div id="create-agent-modal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow">
            <button type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center" data-modal-hide="create-agent-modal">
                <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                </svg>
                <span class="sr-only">Close modal</span>
            </button>
            <div class="px-6 py-6 lg:px-8">
                <h3 class="mb-4 text-xl font-medium text-gray-900">Create a new agent</h3>
                <form class="space-y-6" action="#">
                    <div>
                        <label for="name" class="block mb-2 text-sm font-medium text-gray-900">Name</label>
                        <input type="text" name="name" id="name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" placeholder="Agent's name" required>
                    </div>
                    <div>
                        <label for="note" class="block mb-2 text-sm font-medium text-gray-900">Description</label>
                        <textarea rows="4" type="text" name="note" id="note" placeholder="Describe agent's job" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full p-2.5" required></textarea>
                    </div>
                    <button type="submit" class="w-full text-white bg-indigo-700 hover:bg-indigo-800 focus:ring-4 focus:outline-none focus:ring-indigo-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Create Agent</button>
                </form>
            </div>
        </div>
    </div>
</div> 

OwnerGPT.WebUI.Admin/Views/Home/Tutorial.cshtml
@{
    ViewData["Title"] = "Tutorial";
}

<div class="relative rounded-lg overflow-hidden box-shadow bg-white h-full py-5 px-8">
    <div class="mb-4 lg:mb-0 pb-5 pt-3">
        <h3 class="mb-2 text-xl font-bold text-gray-900">Tutorial</h3>
        <span class="text-base font-normal text-gray-500">This is a list of system's agents</span>
    </div>
</div>